ASPET_recon_outputs:
  src: /home/manu/Manu/ASPET_3ang/software/data/recon/3angle/OUTPUT
  dst: /media/manu/AS_IPC_backup/ASPET/
  every: 
    days: 1
    hrs:  0
    mins: 0 
    secs: 0

ASPET_recon_inputs:
  src: /home/manu/Manu/ASPET_3ang/software/data/recon/3angle/INPUT/
  dst: /media/manu/AS_IPC_backup/ASPET/
